---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: curly
spec:
  replicas: {{.Values.replicas}}
  selector:
    matchLabels:
      app: curly
  template:
    metadata:
      labels:
        app: curly
    spec:
      containers:
        - image: "reselbob/pinger:v2.1"
          imagePullPolicy: Always
          name: curly
          env:
          - name: CURRENT_VERSION
            value: {{.Values.lesson}}
          - name: STOOGE
            value: "I am Curly"
          ports:
            - containerPort: 3000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: larry
spec:
  replicas: {{.Values.replicas}}
  selector:
    matchLabels:
      app: larry
  template:
    metadata:
      labels:
        app: larry
    spec:
      containers:
        - image: "reselbob/pinger:v2.1"
          imagePullPolicy: Always
          name: larry
          env:
          - name: CURRENT_VERSION
            value: {{.Values.lesson}}
          - name: STOOGE
            value: "I am Larry"
          ports:
            - containerPort: 3000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: moe
spec:
  replicas: {{.Values.replicas}}
  selector:
    matchLabels:
      app: moe
  template:
    metadata:
      labels:
        app: moe
    spec:
      containers:
        - image: "reselbob/pinger:v2.1"
          imagePullPolicy: Always
          name: moe
          env:
          - name: CURRENT_VERSION
            value: {{.Values.lesson}}
          - name: STOOGE
            value: "I am Moe"
          ports:
            - containerPort: 3000